# Embed GLSL shader sources into a generated C++ header.
#
# Invoked at build time via: cmake -P EmbedShaders.cmake
# Inputs (passed as -DVAR=value):
#   SHADER_DIR   - directory holding the .glsl sources
#   OUTPUT_FILE  - full path of the header to write
#
# Each shader is wrapped in a raw string literal (delimiter SHADER, which never
# appears in GLSL) and exposed as an inline constexpr const char* in the
# tonemap_shader namespace. Only writes the file if its content would change, so
# it doesn't force a relink on every build when the shaders are untouched.

# name -> source-file basename
set(_SHADERS
    "kVertexSrc=tonemap.vert.glsl"
    "kFragmentSrc=tonemap.frag.glsl"
)

set(_new "#pragma once\n// Generated by cmake/EmbedShaders.cmake from src/ui/shaders/*.glsl — do not edit.\n\nnamespace tonemap_shader {\n\n")

foreach(_entry ${_SHADERS})
    string(REPLACE "=" ";" _parts "${_entry}")
    list(GET _parts 0 _name)
    list(GET _parts 1 _file)
    set(_path "${SHADER_DIR}/${_file}")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "EmbedShaders: missing shader ${_path}")
    endif()
    file(READ "${_path}" _src)
    string(APPEND _new "inline constexpr const char* ${_name} = R\"SHADER(${_src})SHADER\";\n\n")
endforeach()

string(APPEND _new "} // namespace tonemap_shader\n")

set(_old "")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _old)
endif()

if(_new STREQUAL _old)
    message(STATUS "Shaders unchanged")
else()
    file(WRITE "${OUTPUT_FILE}" "${_new}")
    message(STATUS "Shaders embedded -> ${OUTPUT_FILE}")
endif()
