cmake_minimum_required(VERSION 3.21)  # script mode: enables IN_LIST policy

# Embed compiled shader blobs into a generated C++ header.
#
# Invoked at build time via: cmake -P EmbedShaders.cmake
# Inputs (passed as -DVAR=value):
#   SHADER_BLOB_DIR - directory holding the compiled blobs
#   FORMATS         - comma-separated formats to embed (of: spv,dxbc,msl) —
#                     only what the platform's SDL_GPU backends can consume.
#                     The other formats' Blobs are emitted empty and skipped by
#                     VideoTonemap's format selection.
#   OUTPUT_FILE     - full path of the header to write
#
# Each blob (SPIRV/DXIL binary, MSL text) becomes a byte array plus a
# {data,size} Blob in the tonemap_shader namespace. MSL is NUL-padded so it can
# double as a C string; its size excludes the pad byte. Only writes the file if
# its content would change, so it doesn't force a relink on every build when
# the shaders are untouched.

string(REPLACE "," ";" _formats "${FORMATS}")

# name=format=blob-file basename
set(_SHADERS
    "kVertSpirv=spv=tonemap.vert.spv"
    "kVertDxbc=dxbc=tonemap.vert.dxbc"
    "kVertMsl=msl=tonemap.vert.msl"
    "kFragSpirv=spv=tonemap.frag.spv"
    "kFragDxbc=dxbc=tonemap.frag.dxbc"
    "kFragMsl=msl=tonemap.frag.msl"
)

set(_new "#pragma once\n// Generated by cmake/EmbedShaders.cmake from the build-time-compiled\n// blobs of src/ui/shaders/*.hlsl — do not edit.\n\nnamespace tonemap_shader {\n\nstruct Blob {\n    const unsigned char* data;\n    unsigned int size;\n};\n\n")

foreach(_entry ${_SHADERS})
    string(REPLACE "=" ";" _parts "${_entry}")
    list(GET _parts 0 _name)
    list(GET _parts 1 _fmt)
    list(GET _parts 2 _file)
    if(NOT _fmt IN_LIST _formats)
        string(APPEND _new "// Format not used by this platform's SDL_GPU backends.\ninline constexpr Blob ${_name}{nullptr, 0};\n\n")
        continue()
    endif()
    set(_path "${SHADER_BLOB_DIR}/${_file}")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "EmbedShaders: missing shader blob ${_path} — "
            "the shader compile step should have produced it")
    endif()
    file(READ "${_path}" _hex HEX)
    if(_file MATCHES "\\.msl$")
        string(APPEND _hex "00")  # NUL-pad text so it can be used as a C string
        set(_sizeexpr "sizeof(${_name}Data) - 1")
    else()
        set(_sizeexpr "sizeof(${_name}Data)")
    endif()
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n    " _bytes "${_bytes}")
    string(APPEND _new "inline constexpr unsigned char ${_name}Data[] = {\n    ${_bytes}\n};\ninline constexpr Blob ${_name}{${_name}Data, ${_sizeexpr}};\n\n")
endforeach()

string(APPEND _new "} // namespace tonemap_shader\n")

set(_old "")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _old)
endif()

if(_new STREQUAL _old)
    message(STATUS "Shaders unchanged")
else()
    file(WRITE "${OUTPUT_FILE}" "${_new}")
    message(STATUS "Shaders embedded -> ${OUTPUT_FILE}")
endif()
